import imgHaircut from './../images/hair_cut.jpeg';
import imgManicure from './../images/manicure.jpeg';
import imgFacial from './../images/facial_kit_for_women.webp';
import imgHairSpa from './../images/Hair_spa.png';
import imgMakeupWomen from './../images/makeup_women.jpg';
import imgWaxing from './../images/waxing.jpeg';
import imgThreading from './../images/Threading & Eyebrow Shaping.jpg';
import imgPedicure from './../images/pedicure..jpeg';
import imgHairColour from './../images/hair coloring.jpg';
import imgDeepCondition from './../images/Deep Conditioning Hair Treatment.jpeg';
import imgMassage from './../images/Relaxing Body Massage.jpeg';

export const dataObj = [
  {
    id: 1,
    name: 'Haircut',
    category: 'Hair',
    originalPrice: '1050',
    discount: '30%',
    offerPrice: '500',
    durationMinutes: 30,
    description: 'A stylish haircut by our expert stylists.',
    imageUrl: imgHaircut,
    available: true,
    rating: 4.5,
    reviewsCount: 120,
    serviceCode: 'HC-001',
    tags: ['haircut', 'styling'],
    features: ['Wash & blow-dry', 'Expert stylists']
  },
  {
    id: 2,
    name: 'Manicure',
    category: 'Nails',
    originalPrice: '1000',
    discount: '30%',
    offerPrice: '500',
    durationMinutes: 40,
    description: 'Relaxing manicure for beautiful hands.',
    imageUrl: imgManicure,
    available: true,
    rating: 4.4,
    reviewsCount: 85,
    serviceCode: 'MN-002',
    tags: ['manicure', 'nails', 'polish'],
    features: ['Nail shaping', 'Polish & massage']
  },
  {
    id: 3,
    name: 'Facial',
    category: 'Face',
    originalPrice: '1000',
    discount: '30%',
    offerPrice: '500',
    durationMinutes: 50,
    description: 'Rejuvenating facial for glowing skin.',
    imageUrl: imgFacial,
    available: true,
    rating: 4.5,
    reviewsCount: 98,
    serviceCode: 'FC-003',
    tags: ['facial', 'skincare'],
    features: ['Deep cleansing', 'Glow treatment']
  },
  {
    id: 4,
    name: 'Hair Spa',
    category: 'Hair',
    originalPrice: '1500',
    discount: '25%',
    offerPrice: '1125',
    durationMinutes: 60,
    description: 'Nourishing hair spa for soft, shiny hair.',
    imageUrl: imgHairSpa,
    available: true,
    rating: 4.6,
    reviewsCount: 74,
    serviceCode: 'HS-004',
    tags: ['hair-spa', 'nourish'],
    features: ['Scalp massage', 'Deep conditioning']
  },
  {
    id: 5,
    name: 'Makeup',
    category: 'Makeup',
    originalPrice: '2000',
    discount: '20%',
    offerPrice: '1600',
    durationMinutes: 90,
    description: 'Professional makeup for special occasions.',
    imageUrl: imgMakeupWomen,
    available: true,
    rating: 4.6,
    reviewsCount: 65,
    serviceCode: 'MK-005',
    tags: ['makeup', 'special-occasion'],
    features: ['Airbrush option', 'Long-lasting products']
  },
  {
    id: 6,
    name: 'Waxing',
    category: 'Hair Removal',
    originalPrice: '600',
    discount: '10%',
    offerPrice: '540',
    durationMinutes: 30,
    description: 'Quick and gentle waxing for smooth skin. Options: full leg, half leg, arms, underarm, bikini.',
    imageUrl: imgWaxing,
    available: true,
    rating: 4.4,
    reviewsCount: 36,
    serviceCode: 'WX-006',
    tags: ['waxing', 'hair-removal', 'quick'],
    features: ['Hygienic supplies', 'Suitable for sensitive skin']
  },
  {
    id: 7,
    name: 'Threading & Eyebrow Shaping',
    category: 'Face',
    originalPrice: '250',
    discount: '0%',
    offerPrice: '250',
    durationMinutes: 20,
    description: 'Precise threading for eyebrows, upper lip, and face shaping to enhance facial features.',
    imageUrl: imgThreading,
    available: true,
    rating: 4.6,
    reviewsCount: 92,
    serviceCode: 'TH-007',
    tags: ['threading', 'eyebrows', 'shaping'],
    features: ['Precision shaping', 'Quick service']
  },
  {
    id: 8,
    name: 'Pedicure',
    category: 'Nails',
    originalPrice: '800',
    discount: '15%',
    offerPrice: '680',
    durationMinutes: 45,
    description: 'Relaxing pedicure with scrub, massage and polish for soft, healthy feet.',
    imageUrl: imgPedicure,
    available: true,
    rating: 4.5,
    reviewsCount: 54,
    serviceCode: 'PD-008',
    tags: ['pedicure', 'nails', 'spa'],
    features: ['Foot soak', 'Exfoliation', 'Massage']
  },
  {
    id: 9,
    name: 'Hair Colouring',
    category: 'Hair',
    originalPrice: '2500',
    discount: '20%',
    offerPrice: '2000',
    durationMinutes: 120,
    description: 'Professional hair colouring and highlights using quality products to protect hair health.',
    imageUrl: imgHairColour,
    available: true,
    rating: 4.3,
    reviewsCount: 28,
    serviceCode: 'HC-009',
    tags: ['hair', 'colour', 'highlights'],
    features: ['Premium colours', 'Post-care advice']
  },
  {
    id: 10,
    name: 'Bridal Makeup',
    category: 'Makeup',
    originalPrice: '8000',
    discount: '10%',
    offerPrice: '6000',
    durationMinutes: 150,
    description: 'Full bridal makeup and trial, tailored to your look with long-lasting products.',
    imageUrl: imgMakeupWomen,
    available: true,
    rating: 4.8,
    reviewsCount: 18,
    serviceCode: 'BM-010',
    tags: ['bridal', 'makeup', 'special-occasion'],
    features: ['Trial available', 'Airbrush option']
  },
  {
    id: 11,
    name: 'Deep Conditioning Hair Treatment',
    category: 'Hair',
    originalPrice: '1200',
    discount: '15%',
    offerPrice: '1020',
    durationMinutes: 60,
    description: 'Intensive hair treatment to repair and nourish damaged or dry hair.',
    imageUrl: imgDeepCondition,
    available: true,
    rating: 4.5,
    reviewsCount: 40,
    serviceCode: 'HT-011',
    tags: ['hair-treatment', 'conditioning'],
    features: ['Keratin option', 'Scalp therapy']
  },
  {
    id: 12,
    name: 'Relaxing Body Massage',
    category: 'Spa',
    originalPrice: '1800',
    discount: '20%',
    offerPrice: '1440',
    durationMinutes: 60,
    description: 'Swedish/relaxing body massage to reduce stress and improve circulation. Choose oil or dry massage.',
    imageUrl: imgMassage,
    available: true,
    rating: 4.7,
    reviewsCount: 66,
    serviceCode: 'MS-012',
    tags: ['massage', 'spa', 'relaxation'],
    features: ['Aromatherapy option', 'Experienced therapists']
  }
];
